### ISSUE TITLE
getSectionheaderindex(section) always returns -1

### ISSUE THREAD

**Issue by abhishekprince** [afollestad/sectioned-recyclerview#39]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of this library.
- [X] I have given my issue a non-generic title.

###### Include the following:
 - Library version: `0.4.0`
 - Device OS version: `5.0.1`
 - Device Manufacturer: `Coolpad`
 - Device Name: `Note 3`

Adapter method `getSectionHeaderIndex(section)` always return to -1 . seems like it does not found the section but when I call `getSectionCount()` it returns the exact number of section . suppose i have 5 sections and I want to get the index of section 3 it will return -1 should be around 20 or something else depending upon number of items.

     int index= adapter.getSectionHeaderIndex(3); 

###### Expected Result
20

###### Actual Result
-1

**Comment by elmokadim** [comment]
Same problem

**Comment by afollestad** [comment]
Fixed in release 0.4.1.

**Comment by abhishekprince** [comment]
@afollestad not fixed .. update my dependency .. still the same issue

**Comment by abhishekprince** [comment]
@afollestad thanks for fixing this problem
